# Generated by Django 4.2.1 on 2023-05-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
